### ISSUE TITLE
api design: atomic vs non-atomic txn funcs 

### ISSUE THREAD

**Issue by spencercap** [thencc/algonautjs#69]
for the sake of simplicity and onboarding new users without introducing tooo many new terms,
is there a way we can combine the atomic and non-atomic txn methods? 

or do we not care abt this so much? @youraerials @lanidelrey

**Comment by lanidelrey** [comment]
I like it as it is, but my preference is lightly held!

**Comment by spencercap** [comment]
k just bookmarking to talk about tuesday / next week sometime

**Comment by enceladus** [comment]
I don't think onboarding is the issue here, as anyone using algonautjs will be deep enough in Algorand to have probably read [this documentation](https://developer.algorand.org/docs/get-details/atomic_transfers/).

BUT I do agree there's an opportunity for improvement and DRYness here. I haven't given this _too_ much thought, but I think this would be the goal:

```js
// calls sendTransaction() automatically
const result = await algonaut.optInAsset(1234567);

// the same method, without async, returns an unsigned transaction
const result = await algonaut.sendTransaction([
  algonaut.optInAsset(1234567),
  algonaut.optInAsset(2345678)
]);
```

**Comment by enceladus** [comment]
That said, I don't think this is super high priority. It's a very consistent pattern as it is. And it will probably require some significant refactoring and JS magic.
