### ISSUE TITLE
test fails — expect activeWallet to be undefined by default

### ISSUE THREAD

**Issue by enceladus** [thencc/algonautjs#74]
Running just this test causes some cross-contamination. It appears `new Algonaut()` is not clearing the any wallet state.

``` algonaut-offline › expect activeWallet to be undefined by default

    expect(received).toBeUndefined()

    Received:

{
    "accounts": [
        {
            "active": true, 
            "address": "PABEKX52YGCEEOHJQSSOQHZICPGIGPXTFFJVVXBCUYAMKTPAEQE4HRRGPY", 
            "chain": "algorand", 
            "name": "Mnemonic Account 1684871405760", 
            "walletId": "mnemonic"
        }
    ], 
    "activeAccount": {
        "active": true, 
        "address": "PABEKX52YGCEEOHJQSSOQHZICPGIGPXTFFJVVXBCUYAMKTPAEQE4HRRGPY", 
        "chain": "algorand", 
        "name": "Mnemonic Account 1684871405760", 
        "walletId": "mnemonic"
    }, 
    "client": {
        "sdk": {
            "addr": "PABEKX52YGCEEOHJQSSOQHZICPGIGPXTFFJVVXBCUYAMKTPAEQE4HRRGPY", 
            "sk": [125, 217, 6, 236, 87, 245, 156, 165, 107, 247 ]
        }
    }, 
    "connect": [Function connect], 
    "connecting": false, 
    "disconnect": [Function disconnect], 
    "id": "mnemonic", 
    "initParams": "cook bread voyage ****REST OF MNEMONIC REMOVED****", 
    "inited": true, 
    "initing": false, 
    "isActive": true, 
    "isConnected": true, 
    "loadClient": [Function loadClient], 
    "metadata": {
        "chain": "algorand", 
        "icon": "data:image/svg+xml,%3c%3fxml version='1.0' encoding='UTF-8'%3f%3e %3c!-- Generated by Pixelmator Pro 3.2.2 --%3e %3csvg width='409' height='210' viewBox='0 0 409 210' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'%3e%3ctext id='MNEMONIC' xml:space='preserve' x='0' y='129' font-family='Helvetica' font-size='72' fill='black'%3eMNEMONIC%3c/text%3e%3c/svg%3e", 
        "id": "mnemonic", 
        "name": "Mnemonic", 
        "pkg": ""
    }, 
    "reconnect": [Function reconnect], 
    "removeAccounts": [Function removeAccounts], 
    "setAsActiveWallet": [Function setAsActiveWallet], 
    "signTransactions": [Function signTransactions], 
    "signing": false
}```

**Comment by enceladus** [comment]
Ok, so this may or may not be a bug, but either way, we haven't determined what the expected behavior should be. According to the tests, activeWallet should be undefined by default. BUT any-wallet is initializing with a connected account (`"isConnected": true`) when it's not actually connected (I still have to re-auth to sign transactions). I'm not sure if this is true for other wallets, but it's definitely the case with inkey.

And it's strange that this is happening in a node env at all. 

Expected behavior in my mind is:

```const algonaut = new Algonaut();
console.log(algonaut.activeWallet) // "null"
```

Always. Even if there is a cached account. dApps should have an easy way to recover cached accounts (`algonaut.connect()` default behavior perhaps), but they shouldn't be connected upon instantiation.

What do you think @spencercap ?

**Comment by spencercap** [comment]
ah i see. yes, this is the expected behavior. 
though the node env aspect is somewhat surprising. 

any-wallet is trying to be helpful and remember the previously connected account(s) so that the user doesnt have to re-sign-in every page load or have the dev need to handle that. consider the 100yss QR scan flow opening pages in new tabs frequently. this localstorage screenshot explains rather simply that there can be any number of connected accounts across providers or even multiple accounts from the same provider and the activeAccount is one of those:
<img width="577" alt="Screenshot 2023-05-30 at 11 16 56 AM" src="https://github.com/thencc/algonautjs/assets/4987509/fcc7f725-d6fd-4095-a80f-a358f7d8bbe3">

re this issue, what it sounds like is happening is that a previous test is generating a new acct, any-wallet remembers it to the connectedAccts array + activeAcct, and then when algonaut is reinstantiated (`a = new Algonaut()`) for the next test it plugs back in to the any-wallet state in memory (yes this even happens in node currently). i can see how this is a possible security vulnerability on the server-side in particular like when an edge function is processing + signing txns on the behalf of database users (custodial accts). do we want to disable any-wallet's state if NOT in the browser? @youraerials 

also relevant here is the concept we haven't quite introduced yet which is trust level (0 being no acct connect, 1 being its connected/remembered, 2 being inkey trusts this acct's auth for read, and 3 being the algorand chain trusts it for read + writes aka signing). it sounds like what you are expecting from `algonaut.activeWallet` is what i might consider `algonaut.trustedWallet` or when `algonaut.activeWallet.trustIndex >= 2`. also re trust index as i write this out now, `3` should just allow the dapp to show some create/write form inputs. algonaut & any-wallet will ALWAYS require txn approval signing in the wallet's ui since the mnemonic is never made available client-side.

**Comment by spencercap** [comment]
@enceladus 
a quick solve for this could be to add the call `algonaut.disconnectAll()` before that new Algonaut instantiation in the beforeEach hook of the tests you showed me the other day. let me know how goes!

**Comment by enceladus** [comment]
Is there any reason why this test should be returning true?

```js
        test('isOptedIntoAsset returns false with a new account', async () => {
            algonaut.disconnectAll();
            const wallet = algonaut.createWallet();
            await algonaut.mnemonicConnect(wallet.mnemonic);
            const optedIn = await algonaut.isOptedIntoAsset({
                account: algonaut.walletState.activeAddress,
                assetId: asset.createdIndex
            })
            expect(optedIn).toBe(false);
        })
```

**Comment by enceladus** [comment]
@spencercap ok yes there's definitely a bug here. This very simple test fails:

```js
        test('mnemonic connect should update active account', async () => {
            const account = algonaut.createWallet();
            algonaut.disconnectAll();
            await algonaut.connect({ mnemonic: account.mnemonic });
            expect(algonaut.account?.address).toBe(account.address);
        })
```

**Comment by spencercap** [comment]
Looking into this!

**Comment by spencercap** [comment]
> Is there any reason why this test should be returning true?
> 
> ```js
>         test('isOptedIntoAsset returns false with a new account', async () => {
>             algonaut.disconnectAll();
>             const wallet = algonaut.createWallet();
>             await algonaut.mnemonicConnect(wallet.mnemonic);
>             const optedIn = await algonaut.isOptedIntoAsset({
>                 account: algonaut.walletState.activeAddress,
>                 assetId: asset.createdIndex
>             })
>             expect(optedIn).toBe(false);
>         })
> ```
> 
> (`asset` is created in a previous test)

@enceladus - this seems to be correct actually. when an algo account creates a new asset, they are automatically opted-in to it and hold the reserve supply. (there is no circulating supply yet) 

just did this test in an isolated way and check out this chain state for reference:
- [asset](https://testnet.algoexplorer.io/asset/237040851)
- [creater / holder ](https://testnet.algoexplorer.io/address/BJVIWIXUZYEEL2WGAPKVUGZIVWJ5DTFOROJZY5CBGL25WJIR74MFJP2QJU )

**Comment by spencercap** [comment]
> @spencercap ok yes there's definitely a bug here. This very simple test fails:
> 
> ```js
>         test('mnemonic connect should update active account', async () => {
>             const account = algonaut.createWallet();
>             algonaut.disconnectAll();
>             await algonaut.connect({ mnemonic: account.mnemonic });
>             expect(algonaut.account?.address).toBe(account.address);
>         })
> ```

^ and this simple test passes for me...? 🤷‍♂️

i wonder what's going on - let's hop on a call.

**Comment by spencercap** [comment]
only test thats failing for me is `sendAsset successfully sends asset` but it's due to the .to addr not being opted-in before being sent the asset. and for the fresh wallet to opt-in it needs a tiny bit of funding but i expect the test to run an atomic txn where the `testAccountMnemonic` acct send it some funding, the fresh wallet opts-in, and then the `testAccountMnemonic` send the fresh wallet the new asset

**Comment by spencercap** [comment]
> Is there any reason why this test should be returning true?
> 
> ```js
>         test('isOptedIntoAsset returns false with a new account', async () => {
>             algonaut.disconnectAll();
>             const wallet = algonaut.createWallet();
>             await algonaut.mnemonicConnect(wallet.mnemonic);
>             const optedIn = await algonaut.isOptedIntoAsset({
>                 account: algonaut.walletState.activeAddress,
>                 assetId: asset.createdIndex
>             })
>             expect(optedIn).toBe(false);
>         })
> ```
> 
> (`asset` is created in a previous test)

i just realized maybe that you are meaning to check if the newly created wallet in the first line is opted-in instead of the activeAddress in walletState. `algonaut.createWallet` just creates a wallet and returns it - it does not connect it as the active account in algonaut. perhaps that's where the confusion is from? should it connect it too? i believe this method is here for backwards compatibility. in actuality it's a very simple mapping to one of the algosdk methods.

**Comment by spencercap** [comment]
what seems to be happening is that the offline and online jest suites are running in parallel so the any-wallet state is getting confused. from what i'm reading tests in a suite run in series but suites (even in the same file) run in parallel. 

https://stackoverflow.com/a/61386996

> " Multiple describe() statements will execute in parallel though, even if they're in the same file. ", I tried two describe() in one test file, and first describe has a async test case, but found they execute in series. –

**Comment by enceladus** [comment]
Ah ok. But each describe() has its own Algonaut instantiation, so the state should ideally be separate? Or do multiple instances of algonaut share state? This seems like a bug to me.

**Comment by spencercap** [comment]
> Or do multiple instances of algonaut share state? This seems like a bug to me. 

yes, the any-wallet state is shared across multiple Algonaut instances. is it a little magical but this is how the dux web components easily share state. 

--- 

almost done putting together a branch w working unit tests!

and in doing so i came across a relevant bug to all of this. `.disconnect` wasnt unloading / un-initializing the wallet's client lib which is i think the behavior we almost always want, so i squashed it here: 
https://github.com/thencc/any-wallet/commit/4b7854eb938914ab749da9b2ce894351cd63551a

**Comment by spencercap** [comment]
made a branch + PR for working unit tests here:
https://github.com/thencc/algonautjs/pull/80
